// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaeya0-DoJNI_I10hDx7ZS7_tnVneFUCk',
    appId: '1:506242188849:web:6d3c5b2b4e0e065ef43710',
    messagingSenderId: '506242188849',
    projectId: 'patimatch-app-2026-berkay',
    authDomain: 'patiparent.com',
    storageBucket: 'patimatch-app-2026-berkay.firebasestorage.app',
    measurementId: 'G-BX254LTEK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnvWVxN9Y2eg-HpbFK8KyEguCV7BzCVLM',
    appId: '1:506242188849:android:f1aa6179984088d2f43710',
    messagingSenderId: '506242188849',
    projectId: 'patimatch-app-2026-berkay',
    storageBucket: 'patimatch-app-2026-berkay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjkCKH7rRhkiXr-wuJwOx5o6IgKaNjsPo',
    appId: '1:506242188849:ios:0efbe4af9f454596f43710',
    messagingSenderId: '506242188849',
    projectId: 'patimatch-app-2026-berkay',
    storageBucket: 'patimatch-app-2026-berkay.firebasestorage.app',
    iosBundleId: 'com.example.patimatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjkCKH7rRhkiXr-wuJwOx5o6IgKaNjsPo',
    appId: '1:506242188849:ios:0efbe4af9f454596f43710',
    messagingSenderId: '506242188849',
    projectId: 'patimatch-app-2026-berkay',
    storageBucket: 'patimatch-app-2026-berkay.firebasestorage.app',
    iosBundleId: 'com.example.patimatchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaeya0-DoJNI_I10hDx7ZS7_tnVneFUCk',
    appId: '1:506242188849:web:c90a09fc8fd52d44f43710',
    messagingSenderId: '506242188849',
    projectId: 'patimatch-app-2026-berkay',
    authDomain: 'patimatch-app-2026-berkay.firebaseapp.com',
    storageBucket: 'patimatch-app-2026-berkay.firebasestorage.app',
    measurementId: 'G-68RBPZC7GD',
  );
}
